language: go
sudo: required

go:
  - "1.13.x"
  - "1.14.x"
  - "1.15.x"


before_install:
  # Install golangci-lint
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.31.0
  - echo "TRAVIS_GO_VERSION=${TRAVIS_GO_VERSION}"

script:
  - golangci-lint run
  - go test -v -cover -race -covermode=atomic ./...
  - go test -bench=.

after_success:
  - bash <(curl -s https://codecov.io/bash)